export const UI = {
    alert: 'alert',
    asyncLabel: 'asyncLabel',
    pluginTab: 'pluginTab',
    hideTab: 'hideTab',
    visorVisible: 'visorVisible',
    richMarksVisible: 'richMarksVisible',
    markCreatorVisible: 'markCreatorVisible',
    markCursorValue: 'markCursorValue',
    currentRichMark: 'currentRichMark',
    carouselShow: 'carouselShow',
    carouselFull: 'carouselFull',
    serverModal: 'serverModal',
    catalogModal: 'catalogModal',
    grid: 'grid',
    pluginConfigModal: 'pluginConfigModal',
    publishing: 'publishing',
    showGlobalConfig: 'showGlobalConfig',
    showStyleConfig: 'showStyleConfig',
    blockDrag: 'blockDrag',
    showFileUpload: 'showFileUpload',
    showExportModal: 'showExportModal',
    fileUploadTab: 'fileUploadTab',
    showExitModal: 'showExitModal',
    showTour: 'showTour',
    showHelpButton: 'showHelpButton',
    fileModalResult: 'fileModalResult',
};
