import i18n from 'i18next';

export const testState = { present:
        {
            globalConfig: {
                title: "Ediphy",
                canvasRatio: 16 / 9,
                visorNav: {
                    player: true,
                    sidebar: true,
                    keyBindings: true,
                },
                trackProgress: true,
                age: {
                    min: 0,
                    max: 100,
                },
                context: 'school',
                rights: "Public Domain",
                keywords: [],
                typicalLearningTime: {
                    h: 0,
                    m: 0,
                    s: 0,
                },
                version: '1.0.0',
                thumbnail: '',
                status: 'draft',
                structure: 'linear',
                difficulty: 'easy',
            },
            displayMode: "list",
            imagesUploaded: [],
            indexSelected: -1,
            navItemsById: {
                0: {
                    id: 0,
                    children: [],
                    boxes: [],
                    level: 0,
                    type: '',
                    hidden: false,
                },
                "pa-1511252955865": {
                    id: 0,
                    children: [],
                    boxes: ['bo-1511252957954'],
                    level: 0,
                    type: '',
                    hidden: false,
                },
            },
            navItemsIds: ["pa-1511252955865"],
            navItemSelected: 0,
            marksById: {
                "rm-1511252975065": {
                    parent: 'bo-1511252970033',
                    id: "rm-1511252975055",
                    title: "new mark",
                    connectMode: "existing",
                    connection: "pa-1511252955865",
                    displayMode: "navigate",
                    value: "30.95,49.15",
                    color: "#222222",
                    oldConnection: 'cv-1511252975055',
                    newConnection: 'pa-1511252955865',
                },
            },
            containedViewsById: {
                'cv-1511252975055': {
                    id: 'cv-1511252975055',
                    extraFiles: {},
                    boxes: ['bo-1511252952413'],
                    parent: {
                        'bo-1511252957954': [''],
                    },
                },
            },
            boxesById: {
                'bo-1511252957954': {
                    children: [],
                    col: 0,
                    containedViews: [],
                    container: 0,
                    content: "",
                    draggable: true,
                    fragment: {},
                    id: 'bo-1511252957954',
                    level: 0,
                    parent: "pa-1511252955865",
                    position: {
                        type: "absolute",
                        x: "56.57015590200445%",
                        y: "1.5978695073235685%" },
                    resizable: true,
                    row: 0,
                    showTextEditor: false,
                },
                'bo-1511252952413': {
                    children: [],
                    col: 0,
                    containedViews: [],
                    container: 0,
                    content: "",
                    draggable: true,
                    fragment: {},
                    id: 'bo-1511252957954',
                    level: 0,
                    parent: "pa-1511252955865",
                    position: {
                        type: "absolute",
                        x: "56.57015590200445%",
                        y: "1.5978695073235685%" },
                    resizable: true,
                    row: 0,
                    showTextEditor: false,
                },
            },
            viewToolbarsById: { "pa-1511252955865": {},
                'cv-1511252975055': {},
            },
            pluginToolbarsById: { },
            isBusy: "",
            fetchVishResults: { "results": [] },
        },
};
