import i18n from 'i18next';

export const initialState = (config) => { return config.sections_have_content ?
    ({ filesUploaded: {},
        undoGroup: {
            present: {
                status: 'draft',
                everPublished: false,
                globalConfig: {
                    title: i18n.t('course_title'),
                    canvasRatio: config.defaultAspectRatio || 16 / 9,
                    visorNav: {
                        player: true,
                        sidebar: true,
                        keyBindings: true,
                    },
                    trackProgress: true,
                    age: {
                        min: 0,
                        max: 100,
                    },
                    context: 'elementary_school',
                    rights: "public",
                    keywords: [],
                    minTimeProgress: 10,
                    typicalLearningTime: {
                        h: 0,
                        m: 0,
                        s: 0,
                    },
                    version: '1.0.0',
                    thumbnail: '',
                    structure: 'linear',
                    difficulty: 'easy',
                },
                displayMode: "list",
                indexSelected: "se-1467887497411",
                navItemsById: {
                    0: {
                        id: 0,
                        children: ["se-1467887497411"],
                        boxes: [],
                        level: 0,
                        type: '',
                        hidden: false,
                    },
                    "se-1467887497411": {
                        id: "se-1467887497411",
                        isExpanded: true,
                        parent: 0,
                        children: [],
                        hidden: false,
                        linkedBoxes: {},
                        boxes: config.sections_have_content ? ['bs-1467887497412'] : [],
                        level: 1,
                        type: "section",
                        extraFiles: {},
                        // background: "rgb(255, 255, 255)",
                        // customSize: 0,

                    },
                },
                navItemsIds: ['se-1467887497411'],
                navItemSelected: 'se-1467887497411',
                boxesById: {
                    'bs-1467887497412': {
                        id: "bs-1467887497412",
                        parent: "se-1467887497411",
                        container: 0,
                        content: null,
                        type: "sortable",
                        level: -1,
                        col: 0,
                        row: 0,
                        position: { x: 0, y: 0 },
                        width: "100%",
                        height: null,
                        text: null,
                        draggable: false,
                        resizable: false,
                        showTextEditor: false,
                        fragment: {},
                        children: [],
                        sortableContainers: {},
                        containedViews: [],
                    },
                },
                pluginToolbarsById: {
                },
                isBusy: "",
                exercises: {
                    'se-1467887497411': {
                        id: 'se-1467887497411',
                        submitButton: true,
                        trackProgress: false,
                        attempted: false,
                        weight: 10,
                        minForPass: 50,
                        exercises: {},
                        score: 0,
                    },
                },
                viewToolbarsById: {
                    "se-1467887497411": {
                        id: "se-1467887497411",
                        hidden: false,
                        viewName: i18n.t('section'),
                        breadcrumb: 'reduced',
                        courseTitle: 'hidden',
                        documentSubtitle: 'hidden',
                        documentSubtitleContent: i18n.t('subtitle'),
                        documentTitle: 'expanded',
                        documentTitleContent: "",
                        numPage: 'hidden',
                        numPageContent: '1',
                        background: "#ffffff",
                        customSize: 0,
                    },
                },
            },
        } }) :
    ({ filesUploaded: {},
        undoGroup: {
            present: {
                status: 'draft',
                everPublished: false,
                globalConfig: {
                    title: i18n.t('course_title'),
                    canvasRatio: config.defaultAspectRatio || 16 / 9,
                    minTimeProgress: 10,
                    visorNav: {
                        player: true,
                        sidebar: true,
                        keyBindings: true,
                    },
                    trackProgress: true,
                    age: {
                        min: 0,
                        max: 100,
                    },
                    context: 'elementary_school',
                    rights: "public",
                    keywords: [],
                    typicalLearningTime: {
                        h: 0,
                        m: 0,
                        s: 0,
                    },
                    version: '1.0.0',
                    thumbnail: '',
                    structure: 'linear',
                    difficulty: 'easy',
                },
                indexSelected: 'pa-1497983247795',
                boxesById: {
                    "bs-1497983247797":
            {
                id: "bs-1497983247797",
                parent: "pa-1497983247795",
                container: 0,
                level: -1,
                col: 0,
                row: 0,
                position: { x: 0, y: 0, type: "relative" },
                draggable: false,
                resizable: false,
                showTextEditor: false,
                fragment: {},
                children: [],
                sortableContainers: {},
                containedViews: [],
            },
                },
                boxSelected: -1,
                boxLevelSelected: 0,
                marksById: { },
                navItemsIds: ["se-1467887497411", "pa-1497983247795"],
                navItemSelected: "pa-1497983247795",
                navItemsById: {
                    "0": {
                        id: 0,
                        children: ["se-1467887497411"],
                        boxes: [],
                        level: 0,
                        type: "",
                        hidden: false,
                    },
                    "se-1467887497411": {
                        id: "se-1467887497411",
                        isExpanded: true,
                        parent: 0,
                        linkedBoxes: {},
                        children: ["pa-1497983247795"],
                        hidden: false,
                        boxes: [],
                        level: 1,
                        type: "section",
                        extraFiles: {},
                        customSize: 0,
                    },
                    "pa-1497983247795": {
                        id: "pa-1497983247795",
                        isExpanded: true,
                        parent: "se-1467887497411",
                        linkedBoxes: {},
                        children: [],
                        boxes: ["bs-1497983247797"],
                        level: 2,
                        type: "document",
                        hidden: false,
                        extraFiles: {},
                        customSize: 0,
                    },
                },
                containedViewsById: {},
                containedViewSelected: 0,
                displayMode: "list",
                pluginToolbarsById: {
                    "bs-1497983247797": {
                        id: "bs-1497983247797",
                        showTextEditor: false,
                        pluginId: 'sortable_container',
                        state: {},
                        structure: {
                            height: "",
                            width: "",
                            aspectRatio: true,
                            rotation: "",
                            position: "absolute",
                        },
                        style: {
                            backgroundColor: "#ffffff",
                            borderColor: "#000000",
                            borderRadius: 0,
                            borderStyle: "solid",
                            boderWidth: 0,
                            opacity: 1,
                            padding: 0,
                        },
                    },
                },
                viewToolbarsById: {
                    "se-1467887497411": {
                        id: "se-1467887497411",
                        viewName: i18n.t('section'),
                        breadcrumb: 'reduced',
                        courseTitle: 'hidden',
                        documentSubtitle: 'hidden',
                        documentSubtitleContent: i18n.t('subtitle'),
                        documentTitle: 'expanded',
                        documentTitleContent: "",
                        numPage: 'hidden',
                        numPageContent: '1',
                        background: "#ffffff",
                        backgroundAttr: "",
                        aspectRatio: "",
                    },
                    "pa-1497983247795": {
                        id: "pa-1497983247795",
                        viewName: i18n.t('page'),
                        breadcrumb: 'reduced',
                        courseTitle: 'hidden',
                        documentSubtitle: 'hidden',
                        documentSubtitleContent: i18n.t('subtitle'),
                        documentTitle: 'expanded',
                        documentTitleContent: "",
                        numPage: 'hidden',
                        numPageContent: '',
                        background: "#ffffff",
                        backgroundAttr: "",
                        aspectRatio: "",
                    },
                },
                isBusy: "",
                exercises: {
                    'pa-1497983247795': {
                        id: 'pa-1497983247795',
                        submitButton: true,
                        trackProgress: false,
                        attempted: false,
                        weight: 10,
                        minForPass: 50,
                        exercises: {},
                        score: 0,
                    },
                },
            } } });};
